name: nyxforge_ui
description: "NyxForge -- anonymous decentralised social policy bond market"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  ffi: ^2.0.1
  path_provider: ^2.1.5
  intl: any
  encrypt: ^5.0.1
  decimal: ^2.3.3
  unorm_dart: ^0.3.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  sqlite3_flutter_libs: 0.5.40
  bip39: ^1.0.6
  bip32: ^2.0.0
  polyseed: ^0.0.7
  mutex: ^3.1.0
  ledger_flutter_plus: ^1.4.1
  file: ^7.0.0

  cw_core:
    path: packages/cw_core
  cw_monero:
    path: packages/cw_monero
  cw_shared_external:
    path: packages/cw_shared_external

  cake_backup:
    git:
      url: https://github.com/cake-tech/cake_backup.git
      ref: main
  socks5_proxy:
    git:
      url: https://github.com/LacticWhale/socks_dart
      ref: 27ad7c2efae8d7460325c74b90f660085cbd0685
  on_chain:
    git:
      url: https://github.com/cake-tech/on_chain.git
      ref: 096865a8c6b89c260beadfec04f7e184c40a3273
  socks_socket:
    git:
      url: https://github.com/sneurlax/socks_socket
      ref: e6232c53c1595469931ababa878759a067c02e94
  blockchain_utils:
    git:
      url: https://github.com/cake-tech/blockchain_utils
      ref: cake-update-v2
  bech32:
    git:
      url: https://github.com/cake-tech/bech32.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
